import AppKit
import SwilClipCore

/// Watches `NSPasteboard` and reports new content.
///
/// Polling, not notification: macOS has never offered a pasteboard-change
/// callback. `changeCount` is a cheap integer read, so a 500 ms tick costs
/// essentially nothing and matches v1's proven cadence.
@MainActor
final class PasteboardMonitor {
    /// What the poller found. Bytes stay out of the panel's way until stored.
    enum Capture {
        case text(String)
        case image(data: Data, width: Int, height: Int, format: String, thumbnail: Data?)
    }

    /// Pasteboard markers asking clipboard managers to stay out.
    ///
    /// `ConcealedType` is the one that matters: 1Password, Bitwarden, Apple
    /// Passwords and Keychain Access set it when they put a password up.
    /// **Encrypting the store at rest does not make recording these
    /// acceptable** — a captured password is still listed in the panel, still
    /// pasteable by anyone at an unlocked machine, and still in the user's
    /// backups. The other two mark payloads never meant to outlive the paste
    /// that follows them.
    private static let excludedTypes: Set<String> = [
        "org.nspasteboard.concealedtype",
        "org.nspasteboard.transienttype",
        "org.nspasteboard.autogeneratedtype",
    ]

    private let pasteboard: NSPasteboard
    private var timer: Timer?
    private var lastChangeCount: Int
    /// Generations this app wrote itself. Skipping them is what stops a paste
    /// from re-recording its own content as a fresh clip (SC-08).
    private var selfWrittenGenerations: Set<Int> = []

    private let onCapture: (Capture) -> Void

    init(
        pasteboard: NSPasteboard = .general,
        onCapture: @escaping (Capture) -> Void
    ) {
        self.pasteboard = pasteboard
        self.onCapture = onCapture
        // Start from the current generation so launching the app does not
        // re-capture whatever happens to be on the pasteboard.
        self.lastChangeCount = pasteboard.changeCount
    }

    // No deinit: under Swift 6 a nonisolated deinit may not touch actor-isolated
    // state, and the monitor lives for the process anyway. `stop()` is the
    // teardown path, and it runs on the main actor where the timer belongs.

    func start(interval: TimeInterval = 0.5) {
        stop()
        let timer = Timer(timeInterval: interval, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        // `.common` so polling survives menu tracking and window drags, which
        // would otherwise stall the default run-loop mode and drop copies.
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Record that the next generation was written by us.
    ///
    /// Called immediately before writing to the pasteboard, because the write
    /// increments `changeCount` synchronously.
    func markNextWriteAsOurs() {
        selfWrittenGenerations.insert(pasteboard.changeCount + 1)
        // Bounded: only the last few generations can still be pending, and an
        // unbounded set here would leak for the process lifetime.
        if selfWrittenGenerations.count > 8 {
            selfWrittenGenerations = Set(selfWrittenGenerations.sorted().suffix(4))
        }
    }

    private func poll() {
        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return }
        lastChangeCount = current

        if selfWrittenGenerations.remove(current) != nil { return }
        guard let capture = read() else { return }
        onCapture(capture)
    }

    /// Read the current pasteboard, honouring the exclusion markers.
    ///
    /// The marker check looks at declared **types**, not the payload: it is a
    /// zero-length type entry, so it is only visible before anything is read.
    private func read() -> Capture? {
        let declared = (pasteboard.types ?? []).map { $0.rawValue.lowercased() }
        guard !declared.contains(where: Self.excludedTypes.contains) else { return nil }

        // Text first: it is the overwhelmingly common case, and an app that
        // offers both usually means the text.
        if let string = pasteboard.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return .text(string)
        }

        // Prefer PNG, which is both smaller and what most apps put up. TIFF is
        // the fallback, and it is the reason v1 needed a 10 MB rejection rule:
        // an uncompressed TIFF screenshot can be 80 MB. Re-encoding to PNG here
        // removes the problem instead of guarding against it.
        if let png = pasteboard.data(forType: .png), let size = Self.pixelSize(of: png) {
            return .image(
                data: png, width: size.width, height: size.height, format: "png",
                thumbnail: Thumbnail.make(from: png)
            )
        }
        if let tiff = pasteboard.data(forType: .tiff),
           let bitmap = NSBitmapImageRep(data: tiff),
           let png = bitmap.representation(using: .png, properties: [:]) {
            return .image(
                data: png, width: bitmap.pixelsWide, height: bitmap.pixelsHigh, format: "png",
                thumbnail: Thumbnail.make(from: png)
            )
        }
        return nil
    }

    /// Pixel dimensions, read from the image header.
    ///
    /// v1 declared `imageWidth`/`imageHeight` and then never populated them, so
    /// the UI that rendered them was unreachable (SC-17). Reading them at
    /// capture — the one moment the bytes are already in hand — is what makes
    /// the field real rather than decorative.
    private static func pixelSize(of data: Data) -> (width: Int, height: Int)? {
        guard let rep = NSBitmapImageRep(data: data) else { return nil }
        return (rep.pixelsWide, rep.pixelsHigh)
    }
}
