use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub enum ClipType {
    Text,
    Image,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ClipItem {
    pub id: String,
    pub clip_type: ClipType,
    pub content: String,
    pub preview: String,
    pub timestamp: i64,
    #[serde(default)]
    pub pinned: bool,
    pub app_name: Option<String>,
    pub image_width: Option<u32>,
    pub image_height: Option<u32>,
    pub image_format: Option<String>,
}

/// Pasteboard markers that ask clipboard managers to stay out (the
/// nspasteboard.org convention every macOS clipboard tool is expected to
/// honour).
///
/// `ConcealedType` is the one that matters most: it is what 1Password,
/// Keychain Access, Bitwarden and friends set when they put a password on the
/// pasteboard. Encrypting our store at rest does NOT make recording them
/// acceptable — a captured password is still listed in the panel, still
/// pasteable by anyone at the unlocked machine, and still in the user's
/// backups. The other two mark payloads that were never meant to outlive the
/// paste that follows them.
const EXCLUDED_PASTEBOARD_TYPES: &[&str] = &[
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
];

/// Whether this pasteboard generation must be skipped entirely.
///
/// Deliberately checks the declared TYPES rather than the payload: the marker
/// is a zero-length type entry, so it is only visible before anything is read.
pub fn is_excluded_pasteboard<S: AsRef<str>>(declared_types: &[S]) -> bool {
    declared_types.iter().any(|declared| {
        EXCLUDED_PASTEBOARD_TYPES
            .iter()
            .any(|excluded| declared.as_ref().eq_ignore_ascii_case(excluded))
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ordinary_text_pasteboard_is_recorded() {
        let types = ["public.utf8-plain-text", "NSStringPboardType"];
        assert!(!is_excluded_pasteboard(&types));
    }

    #[test]
    fn password_manager_pasteboard_is_skipped() {
        let types = ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"];
        assert!(is_excluded_pasteboard(&types));
    }

    #[test]
    fn transient_and_autogenerated_are_skipped() {
        assert!(is_excluded_pasteboard(&["org.nspasteboard.TransientType"]));
        assert!(is_excluded_pasteboard(&[
            "org.nspasteboard.AutoGeneratedType"
        ]));
    }

    #[test]
    fn marker_matching_ignores_case() {
        assert!(is_excluded_pasteboard(&["ORG.NSPASTEBOARD.CONCEALEDTYPE"]));
    }

    #[test]
    fn the_source_marker_alone_is_not_a_reason_to_skip() {
        // `org.nspasteboard.source` is provenance metadata, not an opt-out —
        // treating it as one would drop ordinary clips from tagged apps.
        let types = ["public.utf8-plain-text", "org.nspasteboard.source"];
        assert!(!is_excluded_pasteboard(&types));
    }

    #[test]
    fn empty_pasteboard_is_not_excluded() {
        let types: [&str; 0] = [];
        assert!(!is_excluded_pasteboard(&types));
    }
}
